# theme: jekyll-theme-cayman
# plugins:
#   - jekyll-relative-links
# relative_links:
#   enabled: true
#   collections: true
remote_theme: pmarsceill/just-the-docs
logo: "/images/bless.png"
# Aux links for the upper right navigation
aux_links:
  "GitHub repository with a sample app":
    - "//github.com/troido/bless-howto"
