# This is a basic workflow to help you get started with Actions

name: Run UI test on firebase test lab

# Controls when the workflow will run
on:
  push:
    branches:
      - add-tests
#  schedule:
#    # * is a special character in YAML so you have to quote this string
#    - cron:  '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Assemble app debug APK
        run: bash ./gradlew app:assembleDebug --stacktrace
      - name: Upload debug app APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Assemble Android Instrumentation Tests
        run: bash ./gradlew assembleDebugAndroidTest
      - name: Upload Android Test APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk


  firebase:
    name: Run UI tests with Firebase Test Lab
    needs: apk
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: app-debug

      - name: Download Android test APK
        uses: actions/download-artifact@v2
        with:
          name: app-debug-androidTest

      - name: Show project structure
        run: ls -R

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.FIREBASE_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_ENCODED_SERVICE_KEY }}

      - name: Use gcloud CLI
        run: gcloud info

      - name: Run Instrumentation Tests in Firebase Test Lab
        run: |
          gcloud firebase test android run --type instrumentation --app app-debug.apk --test app-debug-androidTest.apk --device model=ASUS_X00T_3,version=27,locale=en,orientation=portrait --device model=ASUS_X00T_3,version=28,locale=en,orientation=landscape
